#!/bin/bash

# Smart Motion Detector - Development Environment Setup
# Generated by Planner Agent
# Task: 01 - Project Structure

set -e

echo "========================================"
echo "Smart Motion Detector - Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check Python version
echo ""
echo "Checking Python version..."
PYTHON_VERSION=$(python3 --version 2>&1 | grep -oP '\d+\.\d+')
if (( $(echo "$PYTHON_VERSION >= 3.11" | bc -l) )); then
    echo -e "${GREEN}Python $PYTHON_VERSION OK${NC}"
else
    echo -e "${RED}Python 3.11+ required, found $PYTHON_VERSION${NC}"
    exit 1
fi

# Create virtual environment if needed
if [ ! -d "venv" ]; then
    echo ""
    echo "Creating virtual environment..."
    python3 -m venv venv
    echo -e "${GREEN}Virtual environment created${NC}"
fi

# Activate virtual environment
echo ""
echo "Activating virtual environment..."
source venv/bin/activate
echo -e "${GREEN}Virtual environment activated${NC}"

# Install dependencies
echo ""
echo "Installing Python dependencies..."
pip install --quiet --upgrade pip
pip install --quiet -r requirements.txt
pip install --quiet pyyaml  # For config validation
echo -e "${GREEN}Dependencies installed${NC}"

# Verify module imports
echo ""
echo "Verifying module imports..."
if python3 -c "from src import config, logger, utils" 2>/dev/null; then
    echo -e "${GREEN}All modules import successfully${NC}"
else
    echo -e "${RED}Module import failed${NC}"
    exit 1
fi

# Verify config.yaml structure
echo ""
echo "Verifying config.yaml..."
if python3 -c "import yaml; c=yaml.safe_load(open('config.yaml')); assert all(k in c for k in ['name','version','slug','arch','options','schema'])" 2>/dev/null; then
    echo -e "${GREEN}config.yaml is valid Home Assistant add-on format${NC}"
else
    echo -e "${RED}config.yaml validation failed${NC}"
    exit 1
fi

# Verify Dockerfile
echo ""
echo "Verifying Dockerfile..."
if grep -q "FROM" Dockerfile && grep -q "CMD" Dockerfile; then
    echo -e "${GREEN}Dockerfile structure OK${NC}"
else
    echo -e "${RED}Dockerfile missing required elements${NC}"
    exit 1
fi

# Verify run.sh
echo ""
echo "Verifying run.sh..."
if grep -q "bashio" run.sh; then
    echo -e "${GREEN}run.sh bashio integration OK${NC}"
else
    echo -e "${YELLOW}Warning: run.sh may be missing bashio integration${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: Smart Motion Detector"
echo "Version: 1.0.0"
echo ""
echo "Verified components:"
echo "  - src/config.py    : Configuration dataclasses"
echo "  - src/logger.py    : Logging module"
echo "  - src/utils.py     : Utility functions"
echo "  - config.yaml      : HA add-on configuration"
echo "  - Dockerfile       : Container build file"
echo "  - run.sh           : Entry point script"
echo ""
echo "To run verification tests:"
echo "  python3 -c \"from src import config, logger, utils\""
echo ""
echo "To build Docker image (requires Docker):"
echo "  docker build --build-arg BUILD_FROM=ghcr.io/home-assistant/amd64-base-python:3.11 -t smart-motion ."
echo ""
